import os

Import('env')

util_test_sources = Glob('#build/test/util/*.cpp')

cpp_path='#test'

libs = ['util']					 
testing = [File('/usr/local/lib/libgtest.a'),
		   File('/usr/local/lib/libgtest_main.a'),
		   File('/usr/local/lib/libgmock.a'),
		   File('/usr/local/lib/libgmock_main.a')]
		   
static_libraries = [File('#lib/' + lib + '/lib' + lib + '.a') for lib in libs]

env = env.Clone()
env.Append(LIBS=static_libraries + testing)

env.Append(CPPPATH=cpp_path)

util_test = env.Program(target='util-test',
 						source=util_test_sources)

Import('unitTestRunner')

Command("test.passed", 'util-test', unitTestRunner)
env.Alias('util-test', 'test.passed')