import os

Import('env')

math_sources = Glob('#build/src/math/*.cpp')

libs = ['system', 'util']

static_libraries = [File('#lib/' + lib + '/lib' + lib + '.a') for lib in libs]

env = env.Clone()
env.Append(LIBS=static_libraries)

math_lib = env.Library(target='math', source=math_sources)

for lib in libs:
    env.Append(LIBPATH='#lib/' + lib)
    env.Depends(math_lib, env.Alias(lib))

env.Install('#lib/math', math_lib)
env.Alias('math', '#lib/math')

env.Install('#lib/math', math_lib)
env.Alias('all', '#lib/math')

Import('unitTestRunner')
env.Command("test.passed", '#build/test/math/math-test', unitTestRunner)
env.Alias('math', 'test.passed')